apiVersion: batch/v1
kind: CronJob
metadata:
  name: failing-job
spec:
  schedule: "*/2 * * * *"  # Every 2 minutes
  jobTemplate:
    spec:
      backoffLimit: 2
      template:
        spec:
          containers:
          - name: fail
            image: busybox:1.36
            args:
            - /bin/sh
            - -c
            - exit 1  # Always fail
          restartPolicy: OnFailure
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
