apiVersion: v1
kind: Pod
metadata:
  name: startup-check
  labels:
    test: startup
spec:
  containers:
  - name: slow-start-app
    image: registry.k8s.io/e2e-test-images/agnhost:2.40
    args:
    - liveness
    startupProbe:
      httpGet:
        path: /healthz
        port: 8080
      failureThreshold: 30
      periodSeconds: 10
    livenessProbe:
      httpGet:
        path: /healthz
        port: 8080
      periodSeconds: 10
