apiVersion: v1
kind: Pod
metadata:
    name: apache1
    labels:
      mycka: k8slearning
spec:
    containers:
    - name: mycontainer
      image: docker.io/httpd
      ports:
      - containerPort: 80
