apiVersion: v1
kind: Pod
metadata:
  name: oom-demo
  labels:
    lab: "50"
    exercise: "oom"
spec:
  containers:
    - name: hog
      image: busybox:1.36
      resources:
        limits:
          memory: "10Mi"
        requests:
          memory: "10Mi"
      command: ["/bin/sh", "-c", "tail -f /dev/zero"]
