apiVersion: v1
kind: Pod
metadata:
  name: pending-nodeselector
  labels:
    lab: "50"
    exercise: "pending-nodeselector"
spec:
  nodeSelector:
    disktype: nvme
  containers:
    - name: app
      image: nginx:1.25-alpine
